//
//  ClipboardHistory.swift
//  DynamicNotch
//
//  Historique des derniers textes copiés, en mémoire seulement (rien sur
//  disque, vidé à la fermeture). Les copies marquées confidentielles par les
//  gestionnaires de mots de passe (convention nspasteboard.org) sont ignorées.
//

import AppKit
import Observation

/// Liste ordonnée, du plus récent au plus ancien, sans doublon.
struct ClipboardEntries: Equatable {
    static let capacity = 20

    private(set) var items: [String] = []

    /// Ajoute `text` en tête. Un texte déjà présent remonte en tête au lieu
    /// d'être dupliqué ; un texte vide (ou que des espaces) est ignoré.
    mutating func insert(_ text: String) {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        items.removeAll { $0 == text }
        items.insert(text, at: 0)
        if items.count > Self.capacity {
            items.removeLast(items.count - Self.capacity)
        }
    }

    mutating func removeAll() {
        items.removeAll()
    }
}

enum ClipboardPolicy {
    /// Types posés par les gestionnaires de mots de passe et les apps qui ne
    /// veulent pas être historisées (http://nspasteboard.org).
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword"
    ]

    static func shouldRecord(types: [String]) -> Bool {
        ignoredTypes.isDisjoint(with: types)
    }
}

@MainActor
@Observable
final class ClipboardHistory {
    static let shared = ClipboardHistory()

    private(set) var entries = ClipboardEntries()

    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private var lastChangeCount: Int
    @ObservationIgnored private var timer: Timer?

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    /// macOS ne notifie pas les changements du presse-papiers : on compare
    /// `changeCount` chaque seconde (lecture d'un entier, coût négligeable).
    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let newTimer = Timer(timeInterval: 1, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        newTimer.tolerance = 0.5
        RunLoop.main.add(newTimer, forMode: .common)
        timer = newTimer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        entries.removeAll()
    }

    /// Recopie `text` dans le presse-papiers (il remonte en tête).
    func copy(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        poll()
    }

    func clear() {
        entries.removeAll()
    }

    func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        let types = pasteboard.types?.map(\.rawValue) ?? []
        guard ClipboardPolicy.shouldRecord(types: types),
              let text = pasteboard.string(forType: .string) else { return }
        entries.insert(text)
    }
}
